# config.toml

[server]
# Rechargement automatique en cas de modification du code
runOnSave = true

[theme]
primaryColor = "#1c6dd0"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e5e5e5"
textColor = "#262730"

[layout]
wide = true
