# config.toml

[server]
# Rechargement automatique en cas de modification du code
runOnSave = true

[theme]
# Utilisation du thème clair par défaut
base = "light"

[layout]
# Activer le mode large
wideMode = true
